// First-party pico_phone file, not vendored. Declares the accessor for
// timezone_data.cc (generated by generate_timezone_data.rb). Unlike
// carrier_data.h, this doesn't need to live under phonenumbers/geocoding/
// -- that constraint only applies to files generated by libphonenumber's
// own generate_geocoding_data tool, which hardcodes that include path.
// This generator is first-party too, so it just includes this header
// directly by relative name.

#ifndef PICO_PHONE_TIMEZONE_DATA_H_
#define PICO_PHONE_TIMEZONE_DATA_H_

#include "phonenumbers/geocoding/geocoding_data.h"

namespace i18n {
namespace phonenumbers {

// A single flat prefix -> raw '&'-joined time zone names table. No
// per-language dimension (unlike geocoding/carrier) since time zone
// identifiers aren't translated.
const PrefixDescriptions* get_timezone_descriptions();

}  // namespace phonenumbers
}  // namespace i18n

#endif  // PICO_PHONE_TIMEZONE_DATA_H_
